# Generated by Django 5.2.1 on 2025-06-04 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action", models.CharField(db_index=True, max_length=50)),
                ("resource_type", models.CharField(db_index=True, max_length=50)),
                ("resource_id", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="core_auditl_user_id_7b678c_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="core_auditl_resourc_a674ad_idx",
                    ),
                    models.Index(
                        fields=["timestamp", "action"],
                        name="core_auditl_timesta_368b53_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PIIAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "pii_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Address"),
                            ("phone", "Phone Number"),
                            ("ssn", "Social Security Number"),
                            ("credit_card", "Credit Card"),
                            ("address", "Physical Address"),
                            ("other", "Other PII"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("export", "Export"),
                            ("decrypt", "Decrypt"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                ("record_id", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "accessed_value_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 hash of accessed value",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("access_reason", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="core_piiacc_user_id_482d5c_idx",
                    ),
                    models.Index(
                        fields=["pii_type", "timestamp"],
                        name="core_piiacc_pii_typ_941f99_idx",
                    ),
                    models.Index(
                        fields=["model_name", "record_id"],
                        name="core_piiacc_model_n_1dadd1_idx",
                    ),
                ],
            },
        ),
    ]
