# Generated by Django 5.2.1 on 2025-06-05 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.security.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_income",
                    apps.core.security.fields.EncryptedDecimalField(
                        blank=True,
                        help_text="User's monthly income (encrypted)",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "financial_goals",
                    apps.core.security.fields.EncryptedTextField(
                        blank=True,
                        help_text="User's financial goals and objectives (encrypted)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this profile was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this profile was last updated"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User this profile belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "users_userprofile",
            },
        ),
    ]
