# Generated by Django 5.2.1 on 2025-06-05 23:33

from django.db import migrations, models

import apps.core.security.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backup_codes",
            field=apps.core.security.fields.EncryptedTextField(
                blank=True,
                help_text="2FA backup codes (encrypted, JSON format)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether two-factor authentication is enabled"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=apps.core.security.fields.EncryptedCharField(
                blank=True,
                help_text="TOTP secret key for 2FA (encrypted)",
                max_length=765,
                null=True,
            ),
        ),
    ]
