# Generated by Django 5.2.1 on 2025-06-06 21:59

from django.db import migrations

import apps.core.security.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_add_2fa_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="totp_secret",
            field=apps.core.security.fields.EncryptedCharField(
                blank=True,
                help_text="TOTP secret key for 2FA (encrypted)",
                max_length=765,
                null=True,
            ),
        ),
    ]
