# Generated by Django 5.2.1 on 2025-06-09 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.security.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("expenses", "0008_alter_transaction_merchant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Budget name or description", max_length=255
                    ),
                ),
                (
                    "amount",
                    apps.core.security.fields.EncryptedDecimalField(
                        help_text="Budget amount (encrypted)", max_length=36
                    ),
                ),
                (
                    "amount_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Budget amount for filtering/sorting (non-encrypted)",
                        max_digits=10,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="Budget period start date"),
                ),
                ("period_end", models.DateField(help_text="Budget period end date")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this budget is active (soft delete)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this budget was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this budget was last updated"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category for this budget (optional for overall)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="expenses.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this budget belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "db_table": "budgets_budget",
                "ordering": ["-period_start", "name"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="budgets_bud_user_id_cec771_idx",
                    ),
                    models.Index(
                        fields=["user", "period_start", "period_end"],
                        name="budgets_bud_user_id_9216c3_idx",
                    ),
                    models.Index(
                        fields=["user", "category", "is_active"],
                        name="budgets_bud_user_id_15627d_idx",
                    ),
                    models.Index(
                        fields=["user", "amount_index"],
                        name="budgets_bud_user_id_d3b208_idx",
                    ),
                ],
                "unique_together": {("user", "category", "period_start", "period_end")},
            },
        ),
    ]
