# Generated by Django 5.2.1 on 2025-06-09 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0001_initial"),
        ("expenses", "0009_alter_transaction_merchant"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="alert_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether alerts are enabled for this budget"
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="critical_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Critical alert threshold as percentage (e.g., 100.00 for 100%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="warning_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Warning alert threshold as percentage (e.g., 80.00 for 80%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category for this budget (optional for overall budgets)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="expenses.category",
            ),
        ),
        migrations.CreateModel(
            name="BudgetAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[("WARNING", "Warning"), ("CRITICAL", "Critical")],
                        help_text="Type of alert (WARNING or CRITICAL)",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Alert message describing the threshold violation"
                    ),
                ),
                (
                    "triggered_at_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget utilization percentage when alert was triggered",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False, help_text="Whether this alert has been resolved"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When this alert was resolved", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this alert was created"
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        help_text="Budget this alert is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="budgets.budget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Alert",
                "verbose_name_plural": "Budget Alerts",
                "db_table": "budgets_budgetalert",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["budget", "is_resolved"],
                        name="budgets_bud_budget__6c04cb_idx",
                    ),
                    models.Index(
                        fields=["budget", "alert_type", "is_resolved"],
                        name="budgets_bud_budget__b0a7f4_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="budgets_bud_created_ae3ce7_idx"
                    ),
                ],
                "unique_together": {("budget", "alert_type", "is_resolved")},
            },
        ),
    ]
