# Generated by Django 5.2.1 on 2025-06-06 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.expenses.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Category name", max_length=100)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Category color in hex format (e.g., #FF0000)",
                        max_length=7,
                        null=True,
                        validators=[apps.expenses.models.validate_hex_color],
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for the category",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is active (soft delete)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this category was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this category was last updated"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category for hierarchical structure",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="expenses.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this category belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "expenses_category",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="expenses_ca_user_id_1f350e_idx",
                    ),
                    models.Index(
                        fields=["user", "parent"], name="expenses_ca_user_id_e8a91f_idx"
                    ),
                ],
                "unique_together": {("user", "name", "parent")},
            },
        ),
    ]
