# Generated by Django 5.2.1 on 2025-06-06 00:19

from django.contrib.auth import get_user_model
from django.db import migrations


def create_default_categories_for_existing_users(apps, schema_editor):
    """Create default categories for all existing users."""
    Category = apps.get_model("expenses", "Category")
    User = get_user_model()

    # Import default categories data
    from apps.expenses.default_categories import DEFAULT_CATEGORIES

    # Create default categories for all users who don't have any categories yet
    for user in User.objects.all():
        # Check if user already has categories
        if not Category.objects.filter(user=user).exists():
            # Create default categories for this user
            for category_data in DEFAULT_CATEGORIES:
                # Create parent category
                parent_category = Category.objects.create(
                    name=category_data["name"],
                    user=user,
                    color=category_data["color"],
                    icon=category_data["icon"],
                )

                # Create child categories
                for child_data in category_data["children"]:
                    Category.objects.create(
                        name=child_data["name"],
                        user=user,
                        parent=parent_category,
                        color=child_data["color"],
                        icon=child_data["icon"],
                    )


def reverse_default_categories(apps, schema_editor):
    """Reverse migration - remove default categories."""
    # For safety, we don't automatically delete categories in reverse migration
    # as users may have customized them or added transactions
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_default_categories_for_existing_users,
            reverse_default_categories,
        ),
    ]
