# Generated by Django 5.2.1 on 2025-06-06 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.security.fields
import apps.expenses.models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_auto_20250606_0019"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("expense", "Expense"),
                            ("income", "Income"),
                            ("transfer", "Transfer"),
                        ],
                        help_text="Type of transaction",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    apps.core.security.fields.EncryptedDecimalField(
                        help_text="Transaction amount (encrypted)", max_length=36
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Transaction description", max_length=255
                    ),
                ),
                (
                    "notes",
                    apps.core.security.fields.EncryptedTextField(
                        blank=True,
                        help_text="Additional notes about the transaction (encrypted)",
                        null=True,
                    ),
                ),
                (
                    "merchant",
                    apps.core.security.fields.EncryptedCharField(
                        blank=True,
                        help_text="Merchant or payee name (encrypted)",
                        max_length=2295,
                        null=True,
                    ),
                ),
                ("date", models.DateField(help_text="Transaction date")),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        help_text="Receipt or supporting document",
                        null=True,
                        upload_to=apps.expenses.models.upload_receipt_to,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this transaction is active (soft delete)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this transaction was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this transaction was last updated",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Category for this transaction (required for expenses)"
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="expenses.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this transaction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "expenses_transaction",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="expenses_tr_user_id_8b7e6d_idx",
                    ),
                    models.Index(
                        fields=["user", "transaction_type", "is_active"],
                        name="expenses_tr_user_id_e7180f_idx",
                    ),
                    models.Index(
                        fields=["user", "date"], name="expenses_tr_user_id_228bc5_idx"
                    ),
                    models.Index(
                        fields=["user", "category", "is_active"],
                        name="expenses_tr_user_id_f2a36f_idx",
                    ),
                ],
            },
        ),
    ]
