# Generated by Django 5.2.1 on 2025-06-06 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.security.fields


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_transaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_recurring",
            field=models.BooleanField(
                default=False,
                help_text="Whether this transaction repeats automatically",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="next_occurrence",
            field=models.DateField(
                blank=True,
                help_text="When the next transaction should be generated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="parent_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent transaction for recurring series",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_children",
                to="expenses.transaction",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recurring_end_date",
            field=models.DateField(
                blank=True,
                help_text="When the recurring pattern ends (optional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recurring_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                help_text="How often the transaction repeats",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recurring_interval",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Interval for recurring frequency (e.g., every 2 weeks)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recurring_start_date",
            field=models.DateField(
                blank=True, help_text="When the recurring pattern starts", null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="merchant",
            field=apps.core.security.fields.EncryptedCharField(
                blank=True,
                help_text="Merchant or payee name (encrypted)",
                max_length=2295,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["is_recurring", "next_occurrence"],
                name="expenses_tr_is_recu_7a9fd2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "is_recurring"], name="expenses_tr_user_id_934522_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["parent_transaction"], name="expenses_tr_parent__31c9ab_idx"
            ),
        ),
    ]
