# Generated by Django 5.2.1 on 2025-06-06 21:59

from django.db import migrations

import apps.core.security.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "expenses",
            "0004_transaction_is_recurring_transaction_next_occurrence_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="merchant",
            field=apps.core.security.fields.EncryptedCharField(
                blank=True,
                help_text="Merchant or payee name (encrypted)",
                max_length=2295,
                null=True,
            ),
        ),
    ]
