# Generated by Django

from django.db import migrations


def populate_amount_index(apps, schema_editor):
    """Populate amount_index field with decrypted amount values."""
    Transaction = apps.get_model("expenses", "Transaction")

    # Get all transactions and update amount_index
    for transaction in Transaction.objects.all():
        # Access the amount field which will be decrypted automatically
        transaction.amount_index = transaction.amount
        transaction.save(update_fields=["amount_index"])


def reverse_populate_amount_index(apps, schema_editor):
    """Reverse operation - clear amount_index field."""
    Transaction = apps.get_model("expenses", "Transaction")
    Transaction.objects.update(amount_index=0)


class Migration(migrations.Migration):
    dependencies = [
        (
            "expenses",
            "0006_transaction_amount_index_alter_transaction_merchant_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(populate_amount_index, reverse_populate_amount_index),
    ]
