# Generated by Django 5.2.1 on 2025-06-09 23:05

from django.db import migrations

import apps.core.security.fields


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0008_alter_transaction_merchant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="merchant",
            field=apps.core.security.fields.EncryptedCharField(
                blank=True,
                help_text="Merchant or payee name (encrypted)",
                max_length=2295,
                null=True,
            ),
        ),
    ]
